-- 계정생성
CREATE USER test01 IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT TO test01;


--------------
-- 회원 테이블
CREATE  TABLE   TRIPMEMBER
(
    MEM_ID      VARCHAR2(20)    PRIMARY KEY,
    MEM_PWD     VARCHAR2(20),
    EMAIL       VARCHAR2(50),
    MEM_NAME    VARCHAR2(20),
    TEL         VARCHAR2(30)
);


--------------
-- 메뉴
CREATE TABLE AREA(
    AREACODE    NUMBER(5)   PRIMARY KEY,
    AREANAME    VARCHAR2(20)
);

CREATE TABLE SIGUNGU(
    AREACODE    NUMBER(5),
    SIGUNGUCODE NUMBER(5),
    SIGUNGUNAME VARCHAR2(30),
    NX 			NUMBER(5),
    NY 			NUMBER(5),
    
    CONSTRAINT fk_code FOREIGN KEY(AREACODE)
         REFERENCES AREA(AREACODE) ON DELETE CASCADE
);



--------------
-- 게시판
CREATE TABLE COMMULIST(
    NUM       NUMBER(8)         PRIMARY KEY,
    TAG       VARCHAR2(20),
    TITLE     VARCHAR2(50),
    WRITER    VARCHAR2(20),
    CONTENT   VARCHAR2(4000)
);
